# Generated by Django 4.1.7 on 2024-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pythonregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('photo', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
