# Generated by Django 4.1.7 on 2024-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0002_rename_pythonregister_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('photo', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('payment_id', models.CharField(max_length=25)),
            ],
        ),
    ]
