# Generated by Django 4.1.7 on 2024-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0006_tutorlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorlogs',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
