# Generated by Django 4.1.7 on 2024-06-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0007_tutorlogs_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('certi10', models.FileField(upload_to='')),
                ('certi12', models.FileField(upload_to='')),
                ('degree', models.FileField(upload_to='')),
            ],
        ),
    ]
